Repository Hortali/Hortali-App, pull requests merged in 2022-12, with the labels that each got.

#102 Fix/swift lint
  Hortali-App/.swiftlint.yml
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/iOS-App/General/Extensions/UIImage+Gif.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenMap/InfoGardenMap.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenTime/InfoGardenTime.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenTime/TimeGroup.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
  Hortali-App/iOS-App/Screens/Main/MainController.swift
  Hortali-App/iOS-App/Screens/Onboarding/Views/Cell/OnboardingCell.swift
  Hortali-App/iOS-App/Screens/Onboarding/Views/OnboardingView.swift
  Hortali-App/iOS-App/Screens/PopUp/View/PopUpView.swift
  Hortali-App/iOS-App/Screens/Settings/View/SettingsView.swift
Labels: fixing bug

#104 Update/UI styles
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Design System/Models/Colors/AppColors.swift
  Hortali-App/Shared/Design System/Models/Icons/AppIcons.swift
  Hortali-App/Shared/Design System/Views/Components/LabelExpansive.swift
  Hortali-App/iOS-App/General/FavoriteHandler/FavoriteHandler.swift
  Hortali-App/iOS-App/General/FavoriteHandler/FavoriteInfos.swift
  Hortali-App/iOS-App/Screens/InfoFood/InfoFoodController.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/InfoGardenController.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
Labels: update UI

#99 Empty view setup
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Design System/Views/Components/CollectionGroup/CollectionGroup.swift
  Hortali-App/Shared/Design System/Views/Components/EmptyView/EmptyTexts.swift
  Hortali-App/Shared/Design System/Views/Components/EmptyView/EmptyView.swift
  Hortali-App/iOS-App/Screens/Favorite/FavoriteViewController.swift
  Hortali-App/iOS-App/Screens/Favorite/View/FavoriteView.swift
  Hortali-App/iOS-App/Screens/Garden/GardenController.swift
  Hortali-App/iOS-App/Screens/Garden/Views/GardenView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
  Hortali-App/iOS-App/Screens/Settings/View/SettingsView.swift
Labels: new feature

#107 Feat/copy animation
  Hortali-App/Shared/Design System/Views/Components/ViewLabel.swift
  Hortali-App/iOS-App/Screens/InfoGarden/InfoGardenController.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenMap/InfoGardenMap.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
Labels: new feature

#109 Feat/sasonalidade
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Design System/Models/Colors/AppColors.swift
  Hortali-App/Shared/Models/Food/ManagedFood.swift
  Hortali-App/Shared/Models/Food/ManagedSeasonality.swift
  Hortali-App/Shared/Storage/Data/JSON/foodData.json
  Hortali-App/iOS-App/Screens/Food/View/Cell/FoodCell.swift
  Hortali-App/iOS-App/Screens/InfoFood/InfoFoodController.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
  Hortali-App/iOS-App/Screens/PopUp/View/PopUpView.swift
Labels: new feature

#111 Feat/last update
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Design System/Views/Components/ContainerView.swift
  Hortali-App/Shared/Models/Garden/ManagedGardenData.swift
  Hortali-App/Shared/Storage/Data/DataManager.swift
  Hortali-App/Shared/Storage/Data/Models/DataType.swift
  Hortali-App/iOS-App/General/Delegates/SearchDelegate.swift
  Hortali-App/iOS-App/General/Delegates/System/AppDelegate.swift
  Hortali-App/iOS-App/General/Protocol/CollectionHandler.swift
  Hortali-App/iOS-App/General/Protocol/CustomCell.swift
  Hortali-App/iOS-App/General/Protocol/SearchProtocol.swift
  Hortali-App/iOS-App/Screens/Garden/DataSource/TagCollectionHandler.swift
  Hortali-App/iOS-App/Screens/Garden/GardenController.swift
  Hortali-App/iOS-App/Screens/Garden/Views/Cell/TagCell.swift
  Hortali-App/iOS-App/Screens/Garden/Views/GardenView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/InfoGardenController.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
Labels: new feature, otimization

#113 Criar nova versão para App Store
  Hortali-App/Hortali.xcodeproj/project.pbxproj
Labels: new release
