Repository Hortali/Hortali-App, pull requests merged in 2022-11, with the labels that each got.

#58 Fix/garden view collection
  Hortali-App/Shared/Design System/Views/Components/LabelExpansive.swift
  Hortali-App/Shared/Design System/Views/Custom/Conponents/CustomScroll.swift
  Hortali-App/Shared/Storage/Data/DataManager.swift
  Hortali-App/iOS-App/Screens/Garden/Views/GardenView.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
Labels: fixing bug

#64 Arrumar espaço inicial e final da collection
  Hortali-App/Shared/Design System/Views/Components/CollectionGroup/CollectionGroup.swift
  Hortali-App/Shared/Design System/Views/Components/ContainerView.swift
  Hortali-App/iOS-App/Screens/Favorite/View/FavoriteView.swift
  Hortali-App/iOS-App/Screens/Food/View/FoodView.swift
  Hortali-App/iOS-App/Screens/Garden/Views/GardenView.swift
  Hortali-App/iOS-App/Screens/HourInfo/View/HourInfoView.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
Labels: fixing bug

#66 Arrumar quando os dados são atualizados
  Hortali-App/iOS-App/Screens/Favorite/FavoriteViewController.swift
Labels: fixing bug

#67 Criar nova build
  Hortali-App/Hortali.xcodeproj/project.pbxproj
Labels: new build

#70 Correções pós MVP
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Assets/Assets.xcassets/AppIcon.appiconset/logo.jpg
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Email-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Email-contact.imageset/email-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Facebook-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Facebook-contact.imageset/face-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/General-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/General-contact.imageset/Link-General.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Instagram-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Instagram-contact.imageset/insta-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Ligar-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Ligar-contact.imageset/fone-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Whatsapp-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Whatsapp-contact.imageset/whatts-contact.png
  Hortali-App/Shared/Design System/Views/Components/CollectionGroup/CollectionGroup.swift
  Hortali-App/Shared/Design System/Views/Components/ContainerView.swift
  Hortali-App/Shared/Design System/Views/Components/LabelExpansive.swift
  Hortali-App/Shared/Design System/Views/Components/ViewLabel.swift
  Hortali-App/Shared/Design System/Views/Custom/Conponents/CustomScroll.swift
  Hortali-App/Shared/Storage/Data/DataManager.swift
  Hortali-App/Shared/Storage/Data/JSON/gardenData.json
  Hortali-App/Shared/Storage/Data/Models/FavoriteUpdate.swift
  Hortali-App/iOS-App/General/Delegates/PopGestureDelegate.swift
  Hortali-App/iOS-App/General/Protocol/CustomNavigationProtocol.swift
  Hortali-App/iOS-App/Screens/Favorite/FavoriteViewController.swift
  Hortali-App/iOS-App/Screens/Favorite/View/FavoriteView.swift
  Hortali-App/iOS-App/Screens/Food/FoodController.swift
  Hortali-App/iOS-App/Screens/Food/View/FoodView.swift
  Hortali-App/iOS-App/Screens/Garden/GardenController.swift
  Hortali-App/iOS-App/Screens/Garden/Views/GardenView.swift
  Hortali-App/iOS-App/Screens/HourInfo/View/HourInfoView.swift
  Hortali-App/iOS-App/Screens/InfoFood/InfoFoodController.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/InfoGardenController.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenContact/ContactGroup.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenContact/InfoGardenContact.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenMap/InfoGardenMap.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
  Hortali-App/iOS-App/Screens/Main/CustomNavigationController.swift
  Hortali-App/iOS-App/Screens/Main/MainController.swift
  Hortali-App/iOS-App/Screens/Main/Menu/MenuController.swift
  Hortali-App/iOS-App/Screens/Main/Menu/TabBarProtocol.swift
Labels: new build

#73 Adicionar extensão de GIF
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/General-contact.imageset/Link-General.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/email-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/email-contact.imageset/email-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/face-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/face-contact.imageset/face-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/fone-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/fone-contact.imageset/fone-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/general-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/insta-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/insta-contact.imageset/insta-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/whatts-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/whatts-contact.imageset/whatts-contact.png
  Hortali-App/iOS-App/General/Extensions/UIImage+Gif.swift
  Hortali-App/iOS-App/General/Extensions/iOSDevCenters+GIF.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
Labels: new feature

#77 Fix onboarding review
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/Email-contact.imageset/email-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/General-contact.imageset/Link-General.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/general-contact.imageset/Link-General.png
  Hortali-App/Shared/Assets/CustomFonts/amsterdam.ttf
  Hortali-App/iOS-App/General/Extensions/iOSDevCenters+GIF.swift
  Hortali-App/iOS-App/Info.plist
  Hortali-App/iOS-App/Screens/Garden/GardenController.swift
  Hortali-App/iOS-App/Screens/Garden/Views/GardenView.swift
  Hortali-App/iOS-App/Screens/Onboarding/DataSource/OnboardingDataSource.swift
  Hortali-App/iOS-App/Screens/Onboarding/Delegate/OnboardingDelegate.swift
  Hortali-App/iOS-App/Screens/Onboarding/OnboardingViewController.swift
  Hortali-App/iOS-App/Screens/Onboarding/Protocol/OnboardingProtocol.swift
  Hortali-App/iOS-App/Screens/Onboarding/Views/Cell/OnboardingCell.swift
  Hortali-App/iOS-App/Screens/Onboarding/Views/OnboardingView.swift
Labels: new feature

#82 Atualizar readme para versão da App Store
  README.md
Labels: documentation

#83 Fix/main conflits
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/General-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/email-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/email-contact.imageset/email-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/face-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/face-contact.imageset/face-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/fone-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/fone-contact.imageset/fone-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/general-contact.imageset/Link-General.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/insta-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/insta-contact.imageset/insta-contact.png
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/whatts-contact.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/Contact Icons/whatts-contact.imageset/whatts-contact.png
  Hortali-App/iOS-App/Screens/Onboarding/DataSource/OnboardingDataSource.swift
  README.md
Labels: fixing bug

#87 Adicionar a feature de mudar a visualização
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Design System/Models/Colors/AppColors.swift
  Hortali-App/Shared/Design System/Models/Icons/AppIcons.swift
  Hortali-App/Shared/Design System/Views/Components/MainView.swift
  Hortali-App/iOS-App/Screens/Garden/GardenController.swift
  Hortali-App/iOS-App/Screens/Garden/Model/GardenVisualization.swift
  Hortali-App/iOS-App/Screens/Garden/Views/GardenView.swift
Labels: new feature

#88 Feat/tela configuração
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Assets/Assets.xcassets/Colors App/General/Green_354116.colorset/Contents.json
  Hortali-App/Shared/Design System/Models/Colors/AppColors.swift
  Hortali-App/Shared/Design System/Models/Colors/AppPureColors.swift
  Hortali-App/Shared/Design System/Models/Icons/AppIcons.swift
  Hortali-App/Shared/Design System/Models/Icons/ContactIcon.swift
  Hortali-App/Shared/Design System/Models/Icons/Extension/UIImage+ContactIcon.swift
  Hortali-App/Shared/Design System/Views/Components/LabelExpansive.swift
  Hortali-App/iOS-App/Screens/Main/MainController.swift
  Hortali-App/iOS-App/Screens/Settings/Data Source/SettingsDataSource.swift
  Hortali-App/iOS-App/Screens/Settings/Delegate/SettingsDelegate.swift
  Hortali-App/iOS-App/Screens/Settings/Model/SettingsData.swift
  Hortali-App/iOS-App/Screens/Settings/Protocol/SettingsProtocol.swift
  Hortali-App/iOS-App/Screens/Settings/SettingsController.swift
  Hortali-App/iOS-App/Screens/Settings/View/Cell/SeetingsCell.swift
  Hortali-App/iOS-App/Screens/Settings/View/SettingsView.swift
Labels: new feature, update UI

#96 Feat/pop up
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Black.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Bold.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Heavy.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Light.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Medium.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Regular.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Semibold.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Thin.otf
  Hortali-App/Shared/Assets/CustomFonts/SF-Pro/SF-Pro-Rounded-Ultralight.otf
  Hortali-App/Shared/Design System/Models/Colors/AppColors.swift
  Hortali-App/Shared/Design System/Models/Font/AppFonts.swift
  Hortali-App/Shared/Design System/Models/Font/Extensions/UIButton+FontInfo.swift
  Hortali-App/Shared/Design System/Models/Font/Extensions/UIFont+setupFont.swift
  Hortali-App/Shared/Design System/Models/Font/FontInfo.swift
  Hortali-App/Shared/Design System/Models/Font/FontWeight.swift
  Hortali-App/Shared/Design System/Views/Components/ContainerView.swift
  Hortali-App/Shared/Models/Food/ManagedFoodData.swift
  Hortali-App/Shared/Models/Food/ManagedVitamins.swift
  Hortali-App/Shared/Storage/Data/DataManager.swift
  Hortali-App/Shared/Storage/Data/JSON/foodData.json
  Hortali-App/Shared/Storage/Data/Models/DataType.swift
  Hortali-App/iOS-App/Info.plist
  Hortali-App/iOS-App/Screens/Garden/GardenController.swift
  Hortali-App/iOS-App/Screens/InfoFood/InfoFoodController.swift
  Hortali-App/iOS-App/Screens/InfoFood/View/InfoFoodView.swift
  Hortali-App/iOS-App/Screens/PopUp/Model/PopUpInfo.swift
  Hortali-App/iOS-App/Screens/PopUp/PopUpController.swift
  Hortali-App/iOS-App/Screens/PopUp/View/PopUpView.swift
Labels: new feature, update UI

#89 Update/horario funcionamento
  Hortali-App/Shared/Storage/Data/JSON/gardenData.json
  Hortali-App/iOS-App/Screens/HourInfo/View/Cell/HourInfoCell.swift
  Hortali-App/iOS-App/Screens/HourInfo/View/HourInfoView.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenTime/InfoGardenTime.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenTime/TimeGroup.swift
Labels: update UI

#97 Update/celula info hortas
  Hortali-App/Hortali.xcodeproj/project.pbxproj
  Hortali-App/Shared/Assets/Assets.xcassets/ReportIcon.imageset/Contents.json
  Hortali-App/Shared/Assets/Assets.xcassets/ReportIcon.imageset/ReportIcon 1.png
  Hortali-App/Shared/Assets/Assets.xcassets/ReportIcon.imageset/ReportIcon.png
  Hortali-App/Shared/Design System/Views/Components/ViewLabel.swift
  Hortali-App/Shared/Storage/Data/JSON/gardenData.json
  Hortali-App/iOS-App/Screens/InfoGarden/DataSource/InfoGardenInfosDataSource.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/InfoGardenInfosCell.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenCellType.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenContact/ContactGroup.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenContact/InfoGardenContact.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenMap/InfoGardenMap.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenReport/InfoGardenReport.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenTime/InfoGardenTime.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/Cells/InfosCell/Types/InfoGardenTime/TimeGroup.swift
  Hortali-App/iOS-App/Screens/InfoGarden/View/InfoGardenView.swift
Labels: update UI
